name: areteia_ai

services:
  python_rag:
    build: ./areteia_ai
    container_name: python_rag
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./areteia_ai:/app
      - hf_cache:/root/.cache/huggingface

volumes:
  hf_cache:
